# version: "3.8"
# services:
#   client:
#     build:
#       context: .
#       dockerfile: Dockerfile.client
#     ports:
#       - "5173:5173"

#   server:
#     build:
#       context: .
#       dockerfile: Dockerfile.server
#     ports:
#       - "5000:5000"

version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./server
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: users
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build: ./client
    restart: always
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql-data:

