openapi: 3.0.0
info:
  title: Full Stack API
  description: API documentation for the Node.js + Express backend
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /api/hello:
    get:
      summary: Greet from the backend
      tags:
        - Greeting
      responses:
        '200':
          description: A simple greeting response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from the backend!
